version: 2
jobs:
    machine:
      image: circleci/classic:latest

dependencies:
  override:
    - sudo pip install awscli

test:
  override:

deployment:
  staging:
    branch: master
    commands:
    - echo "hello world"
 #   - ./deploy_staging.sh
