version: 2

jobs:
  "buildp":
    docker:
      - image: docker:17.06.1-ce-git
    steps:
      # Initialization.
      - checkout
      - setup_remote_docker
      - run:
          name: Installation of build dependencies.
          command: apk add --no-cache bash

      - run:
          name: Installing AWS client
          command: |
            apk add --no-cache jq py-pip sudo
            sudo pip install awscli --upgrade

      - run:
          name: Check for Git Secrets
          command: | 
             git clone https://github.com/awslabs/git-secrets
             cd git-secrets
             make install
             git secrets --install ~/.git-templates/git-secrets
             git config --global init.templateDir ~/.git-templates/git-secrets
             git secrets --register-aws --global
             git secrets --scan -r
             cd ..

workflows:
  version: 2
  build:
    jobs:
      - "buildp":
          filters:
            branches:
              only: master
