version: 2

jobs:
  "buildp":
    docker:
      - image: docker:17.06.1-ce-git
    steps:
      # Initialization.
      - checkout
      - setup_remote_docker
      - run:
          name: Installation of build dependencies.
          command: |
             apk update \
             apk upgrade \
             apk --no-cache add --update tcl apache2 ca-certificates \
             sudo apt-get install build-essential \
             sudo apt-get install -y sudo \
             sudo apt-get install make


      - run:
          name: Check for Git Secrets
          command: |   
             pwd 
             printenv 
             git clone https://github.com/awslabs/git-secrets 
             cd git-secrets
             sudo make install 
             #git secrets --install ~/.git-templates/git-secrets \
             #git config --global init.templateDir ~/.git-templates/git-secrets \
             #git secrets --register-aws --global 
             #git secrets --scan -r ~/project

workflows:
  version: 2
  build:
    jobs:
      - "buildp":
          filters:
            branches:
              only: master
